import { useLanguage } from '@/lib/i18n';
import { motion } from 'framer-motion';

export default function Privacy() {
  const { lang } = useLanguage();
  const content = {
    en: { title: 'Privacy Policy', intro: 'MobiHero operates this website to provide you with an individual user experience. This privacy policy describes how we collect, use, or share personal data.', sections: [{ heading: 'What Personal Data Do We Collect?', content: 'Contact data, communication data, device information, and usage information.' },{ heading: 'Sources of Personal Data', content: 'Directly from you, automatically via cookies, from service providers and partners.' },{ heading: 'How Do We Use Your Data?', content: 'For providing and improving the website, marketing, security, communication, and legal compliance.' },{ heading: 'How Do We Share Personal Data?', content: 'With service providers, marketing partners, within our corporate group, and as required by law.' },{ heading: 'Third-Party Links', content: 'We assume no responsibility for third-party website contents.' },{ heading: 'Children\'s Data', content: 'The website is not intended for children.' },{ heading: 'Data Security', content: 'We implement appropriate technical and organizational measures to protect your data.' },{ heading: 'Your Rights', content: 'You have the right to access, correct, delete, and restrict processing of your data.' },{ heading: 'International Transfers', content: 'Data may be transferred outside the EU if appropriate safeguards exist.' },{ heading: 'Changes to This Policy', content: 'We reserve the right to update this privacy policy at any time.' },{ heading: 'Contact', content: 'MobiHero GmbH, Braunstr. 7, 81545 München. Email: support@mobihero.de, Phone: +49 176 550 64000' }] },
    de: { title: 'Datenschutzerklärung', intro: 'MobiHero betreibt diese Website, um Ihnen ein individuelles Nutzungserlebnis bereitzustellen.', sections: [{ heading: 'Welche Daten erfassen wir?', content: 'Kontaktdaten, Kommunikationsdaten, Geräteinformationen und Nutzungsinformationen.' },{ heading: 'Quellen personenbezogener Daten', content: 'Direkt von Ihnen, automatisch über Cookies, von Dienstanbietern und Partnern.' },{ heading: 'Wie verwenden wir Ihre Daten?', content: 'Zur Bereitstellung der Website, Marketing, Sicherheit und Einhaltung gesetzlicher Verpflichtungen.' },{ heading: 'Weitergabe von Daten', content: 'An Dienstleister, Partner, innerhalb der Unternehmensgruppe und gemäß gesetzlicher Pflichten.' },{ heading: 'Links Dritter', content: 'Für externe Inhalte übernehmen wir keine Verantwortung.' },{ heading: 'Daten von Kindern', content: 'Die Website ist nicht für Kinder bestimmt.' },{ heading: 'Datensicherheit', content: 'Wir setzen angemessene technische und organisatorische Maßnahmen ein.' },{ heading: 'Ihre Rechte', content: 'Sie haben das Recht auf Auskunft, Berichtigung, Löschung und Einschränkung der Verarbeitung.' },{ heading: 'Internationale Übertragungen', content: 'Daten können in Drittländer übertragen werden, sofern geeignete Schutzmaßnahmen bestehen.' },{ heading: 'Änderungen', content: 'Wir behalten uns vor, diese Datenschutzerklärung jederzeit anzupassen.' },{ heading: 'Kontakt', content: 'MobiHero GmbH, Braunstr. 7, 81545 München. E-Mail: support@mobihero.de, Tel: +49 176 550 64000' }] },
  };
  const t = content[lang] || content.en;
  return (
    <div className="min-h-screen bg-background"><section className="py-24"><div className="max-w-4xl mx-auto px-6"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="space-y-8"><h1 className="text-4xl font-bold text-foreground">{t.title}</h1><p className="text-muted-foreground leading-relaxed">{t.intro}</p><div className="space-y-8 text-muted-foreground leading-relaxed">{t.sections.map((section, i) => (<motion.div key={i} initial={{ opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.05 }} className="border-b border-border pb-6 last:border-b-0"><h2 className="text-lg font-semibold text-foreground mb-3">{section.heading}</h2><p>{section.content}</p></motion.div>))}</div></motion.div></div></section></div>
  );
}