import { useLanguage } from '@/lib/i18n';
import { motion } from 'framer-motion';

export default function Terms() {
  const { lang } = useLanguage();
  const content = {
    en: { title: 'Terms and Conditions', sections: [{ heading: '1. Scope of Application', content: 'These General Terms and Conditions apply to the use of the website of MobiHero GmbH, Braunstr. 7, 81545 München, Germany. This website is exclusively for business users in the sense of § 14 BGB (B2B).' },{ heading: '2. Website Contents', content: 'The contents provided on this website serve exclusively for general information about the company, its activities and service portfolio. All displayed information does not constitute binding offers in the legal sense.' },{ heading: '3. No Contract Conclusion via Website', content: 'No contract conclusion is possible via this website. Inquiries via the contact form are not binding offers but serve only for non-binding contact.' },{ heading: '4. Website Usage', content: 'Website usage is only permitted within the scope of applicable law.' },{ heading: '5. Intellectual Property', content: 'All contents of this website are protected by copyright. Use without express written consent of MobiHero GmbH is not permitted.' },{ heading: '6. Liability for Contents', content: 'MobiHero GmbH assumes no liability for the accuracy, completeness and timeliness of the contents provided.' },{ heading: '7. Liability for Links', content: 'This website contains links to external websites. MobiHero GmbH assumes no liability for them.' },{ heading: '8. Limitation of Liability', content: 'The liability of MobiHero GmbH is excluded to the extent permitted by law.' },{ heading: '9. Data Protection', content: 'Information on the processing of personal data is governed in the separate privacy policy.' },{ heading: '10. Applicable Law', content: 'EU law and supplementary German law apply, excluding CISG.' },{ heading: '11. Jurisdiction', content: 'Place of jurisdiction is the location of MobiHero GmbH in Munich, Germany.' },{ heading: '12. Final Provisions', content: 'Should individual provisions be invalid, the remaining provisions remain unaffected.' }] },
    de: { title: 'Allgemeine Geschäftsbedingungen (AGB)', sections: [{ heading: '1. Geltungsbereich', content: 'Diese AGB gelten für die Nutzung der Website der MobiHero GmbH, Braunstr. 7, 81545 München. Diese Website richtet sich ausschließlich an Unternehmer im Sinne von § 14 BGB (B2B).' },{ heading: '2. Inhalte der Website', content: 'Die Inhalte dienen ausschließlich der allgemeinen Information. Alle dargestellten Informationen stellen keine verbindlichen Angebote dar.' },{ heading: '3. Kein Vertragsschluss', content: 'Ein Vertragsschluss über diese Website ist nicht möglich.' },{ heading: '4. Nutzung der Website', content: 'Die Nutzung der Website ist nur im Rahmen der geltenden Gesetze zulässig.' },{ heading: '5. Geistiges Eigentum', content: 'Sämtliche Inhalte sind urheberrechtlich geschützt.' },{ heading: '6. Haftung für Inhalte', content: 'MobiHero GmbH übernimmt keine Gewähr für die Richtigkeit der Inhalte.' },{ heading: '7. Haftung für Links', content: 'Für externe Inhalte wird keine Haftung übernommen.' },{ heading: '8. Haftungsbeschränkung', content: 'Die Haftung ist soweit gesetzlich zulässig ausgeschlossen.' },{ heading: '9. Datenschutz', content: 'Informationen sind in der separaten Datenschutzerklärung geregelt.' },{ heading: '10. Anwendbares Recht', content: 'Es gilt deutsches Recht unter Ausschluss des UN-Kaufrechts.' },{ heading: '11. Gerichtsstand', content: 'Gerichtsstand ist München, Deutschland.' },{ heading: '12. Schlussbestimmungen', content: 'Unwirksame Bestimmungen lassen die Wirksamkeit der übrigen unberührt.' }] },
  };
  const t = content[lang] || content.en;
  return (
    <div className="min-h-screen bg-background"><section className="py-24"><div className="max-w-4xl mx-auto px-6"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="space-y-8"><h1 className="text-4xl font-bold text-foreground">{t.title}</h1><div className="space-y-8 text-muted-foreground leading-relaxed">{t.sections.map((section, i) => (<motion.div key={i} initial={{ opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.05 }} className="border-b border-border pb-6 last:border-b-0"><h2 className="text-lg font-semibold text-foreground mb-3">{section.heading}</h2><p>{section.content}</p></motion.div>))}</div></motion.div></div></section></div>
  );
}